// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjMqvxKQbpJXjYZjFffQPAt16LK-iiT1Q',
    appId: '1:659528987230:web:371b8be382ee1f96087acf',
    messagingSenderId: '659528987230',
    projectId: 'viva-analytics-135d4',
    authDomain: 'viva-analytics-135d4.firebaseapp.com',
    storageBucket: 'viva-analytics-135d4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVhrWtjniR-_LhHKW1fokVin0-Iif495A',
    appId: '1:659528987230:android:c1f823acf351e5d8087acf',
    messagingSenderId: '659528987230',
    projectId: 'viva-analytics-135d4',
    storageBucket: 'viva-analytics-135d4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxCZqvUZoBT6VBv9coYfiW72wchJm6K8U',
    appId: '1:659528987230:ios:97b9bff244c4a47d087acf',
    messagingSenderId: '659528987230',
    projectId: 'viva-analytics-135d4',
    storageBucket: 'viva-analytics-135d4.firebasestorage.app',
    iosBundleId: 'com.vivamatrimony.vivaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxCZqvUZoBT6VBv9coYfiW72wchJm6K8U',
    appId: '1:659528987230:ios:97b9bff244c4a47d087acf',
    messagingSenderId: '659528987230',
    projectId: 'viva-analytics-135d4',
    storageBucket: 'viva-analytics-135d4.firebasestorage.app',
    iosBundleId: 'com.vivamatrimony.vivaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjMqvxKQbpJXjYZjFffQPAt16LK-iiT1Q',
    appId: '1:659528987230:web:9b18535a7e3e0eef087acf',
    messagingSenderId: '659528987230',
    projectId: 'viva-analytics-135d4',
    authDomain: 'viva-analytics-135d4.firebaseapp.com',
    storageBucket: 'viva-analytics-135d4.firebasestorage.app',
  );
}
