/// Community constants for the Vishwakarma community.
/// Used in dropdowns across onboarding, edit-profile, and search filter screens.
class CommunityConstants {
  CommunityConstants._();

  static const String defaultCaste    = 'Vishwakarma';
  static const String defaultSubCaste = 'Panchal';

  /// Top-level caste list. Keeps a short list; other castes are free-text.
  static const List<String> castes = [
    'Vishwakarma',
    'Brahmin',
    'Rajput',
    'Jat',
    'Yadav',
    'Patel / Patidar',
    'Agarwal / Baniya',
    'Kayastha',
    'Maratha',
    'Nair',
    'Vokkaliga',
    'Lingayat',
    'Reddy',
    'Kamma',
    'Naidu',
    'Scheduled Caste',
    'Scheduled Tribe',
    'Other / Not Listed',
  ];

  static const List<String> vishwakarmaSubCastes = [
    'Panchal',
    'Dhiman',
    'Badhai',
    'Sonar',
    'Jangid',
    'Suthar',
    'Sutar',
    'Lohar',
    'Tarkhan',
    'Khati',
    'Ramgarhia',
    'Mistry',
    'Gajjar',
    'Pancholi',
    'Karmakar',
    'Sutradhar',
    'Maharana',
    'Moharana',
    'Kammalar',
    'Kammara',
    'Kamsali',
    'Kammari',
    'Kanchari',
    'Vadrangi',
    'Badiger',
    'Achari',
    'Acharya',
    'Silpi',
    'Kollan',
    'Musari',
    'Thattan',
    'Other / Not Listed',
  ];

  /// Deduped list of common gotras (Vishwakarma-relevant + common Hindu gotras).
  static const List<String> vishwakarmaGotras = [
    'Bharadwaj',
    'Kashyap',
    'Vashishtha',
    'Gautam',
    'Kaushik',
    'Atri',
    'Jamadagni',
    'Vishwamitra',
    'Bhrigu',
    'Angirasa',
    'Agastya',
    'Shandilya',
    'Vatsa',
    'Parashar',
    'Garg',
    'Mudgal',
    'Kaundinya',
    'Katyayan',
    'Bhargava',
    'Harit',
    'Kapil',
    'Kanva',
    'Lohit',
    'Marichi',
    'Pulaha',
    'Pulastya',
    'Sankhyan',
    'Saunaka',
    'Sandilya',
    'Manu',
    'Manu Brahma',
    'Maya',
    'Maya Brahma',
    'Tvashtha',
    'Tvashtha Brahma',
    'Shilpi',
    'Shilpi Brahma',
    'Vishvajna',
    'Vishvajna Brahma',
    'Other / Not Listed',
    'Not Sure',
    'No Gotra',
  ];
}
